var soundBGM=new Howl({src:["pianoloop118bpm.mp3"],loop:!0,volume:.5}),soundBallRemove=new Howl({src:["spcvactub.mp3"],volume:.5}),soundGameOver=new Howl({src:["notification.mp3"],volume:.5}),soundNewBall=new Howl({src:["soundNewBall.wav"]}),soundControlButton=new Howl({src:["controlbtn.wav"]}),ballsMin=10,ballsMax=100,ballCount=10,balls=[],ballsKilled=[],intervals=[],missed=[],missedBalls=0,timeStarted,timeFinished,timeInterval,timeChecked,timer,windows=[],soundIdBGM=null,ballSpeed=30,timeToNext=
1500,colorBallBorder="red",addBallOnMissed=!0,colorNameHex=["aliceblue;antiquewhite;aqua;aquamarine;azure;beige;bisque;black;blanchedalmond;blue;blueviolet;brown;burlywood;cadetblue;chartreuse;chocolate;coral;cornflowerblue;cornsilk;crimson;cyan;darkblue;darkcyan;darkgoldenrod;darkgray;darkgrey;darkgreen;darkkhaki;darkmagenta;darkolivegreen;darkorange;darkorchid;darkred;darksalmon;darkseagreen;darkslateblue;darkslategray;darkslategrey;darkturquoise;darkviolet;deeppink;deepskyblue;dimgray;dimgrey;dodgerblue;firebrick;floralwhite;forestgreen;fuchsia;gainsboro;ghostwhite;gold;goldenrod;gray;grey;green;greenyellow;honeydew;hotpink;indianred ;indigo  ;ivory;khaki;lavender;lavenderblush;lawngreen;lemonchiffon;lightblue;lightcoral;lightcyan;lightgoldenrodyellow;lightgray;lightgrey;lightgreen;lightpink;lightsalmon;lightseagreen;lightskyblue;lightslategray;lightslategrey;lightsteelblue;lightyellow;lime;limegreen;linen;magenta;maroon;mediumaquamarine;mediumblue;mediumorchid;mediumpurple;mediumseagreen;mediumslateblue;mediumspringgreen;mediumturquoise;mediumvioletred;midnightblue;mintcream;mistyrose;moccasin;navajowhite;navy;oldlace;olive;olivedrab;orange;orangered;orchid;palegoldenrod;palegreen;paleturquoise;palevioletred;papayawhip;peachpuff;peru;pink;plum;powderblue;purple;rebeccapurple;red;rosybrown;royalblue;saddlebrown;salmon;sandybrown;seagreen;seashell;sienna;silver;skyblue;slateblue;slategray;slategrey;snow;springgreen;steelblue;tan;teal;thistle;tomato;turquoise;violet;wheat;white;whitesmoke;yellow;yellowgreen".split(";"),
"f0f8ff faebd7 00ffff 7fffd4 f0ffff f5f5dc ffe4c4 000000 ffebcd 0000ff 8a2be2 a52a2a deb887 5f9ea0 7fff00 d2691e ff7f50 6495ed fff8dc dc143c 00ffff 00008b 008b8b b8860b a9a9a9 a9a9a9 006400 bdb76b 8b008b 556b2f ff8c00 9932cc 8b0000 e9967a 8fbc8f 483d8b 2f4f4f 2f4f4f 00ced1 9400d3 ff1493 00bfff 696969 696969 1e90ff b22222 fffaf0 228b22 ff00ff dcdcdc f8f8ff ffd700 daa520 808080 808080 008000 adff2f f0fff0 ff69b4 cd5c5c 4b0082 fffff0 f0e68c e6e6fa fff0f5 7cfc00 fffacd add8e6 f08080 e0ffff fafad2 d3d3d3 d3d3d3 90ee90 ffb6c1 ffa07a 20b2aa 87cefa 778899 778899 b0c4de ffffe0 00ff00 32cd32 faf0e6 ff00ff 800000 66cdaa 0000cd ba55d3 9370db 3cb371 7b68ee 00fa9a 48d1cc c71585 191970 f5fffa ffe4e1 ffe4b5 ffdead 000080 fdf5e6 808000 6b8e23 ffa500 ff4500 da70d6 eee8aa 98fb98 afeeee db7093 ffefd5 ffdab9 cd853f ffc0cb dda0dd b0e0e6 800080 663399 ff0000 bc8f8f 4169e1 8b4513 fa8072 f4a460 2e8b57 fff5ee a0522d c0c0c0 87ceeb 6a5acd 708090 708090 fffafa 00ff7f 4682b4 d2b48c 008080 d8bfd8 ff6347 40e0d0 ee82ee f5deb3 ffffff f5f5f5 ffff00 9acd32".split(" ")];
function colorReverse(a){if(0>a.indexOf(",")){var b=colorNameHex[0].indexOf(a);a=255-parseInt("0x"+colorNameHex[1][b].slice(0,2));var c=255-parseInt("0x"+colorNameHex[1][b].slice(2,4)),b=255-parseInt("0x"+colorNameHex[1][b].slice(4));return"rgb("+a+","+c+","+b+")"}a=a.replace("rgb(","");a=a.replace(")","");a=a.split(",");return a="rgb("+(255-1*a[0])+","+(255-1*a[1])+","+(255-1*a[2])+")"}
function Game(){this.timeStart=timeStarted;this.timeFinish=timeFinished;this.timeInverval=timeFinished-timeStarted;this.ballTotal=ballCount;this.windowSize=windows[windows.length-1]}function windowStamp(){var a=[];a.push(window.innerWidth);a.push(window.innerHeight);windows.push(a)}function showGameReport(){$("#gameresult").slideDown();soundGameOver.play()}
var divOnMouseOver=function(a){var b=-1,c,d;for(d in balls)if(balls[d].ball===a){b=d;c=new Date;break}if(0<=b&&balls[b].selected){intervals.push(c-timeChecked);document.body.style.backgroundColor=balls[b].ball.style.backgroundColor;b=balls.splice(b,1);ballsKilled.unshift(b);timeChecked=new Date;missed.push(missedBalls);for(b=1;b<=missedBalls;b++)rotateBalls(0);missedBalls=0;$(a).fadeOut(400);soundBallRemove.play();document.getElementById("ballsleft").innerHTML=balls.length;0>=balls.length?(document.getElementById("timefinish").innerHTML=
getTimeStamp(2),clearInterval(timer),document.body.style.backgroundColor="white",document.getElementById("control").style.visibility="visible",document.getElementById("control2").style.visibility="visible",ballsMin=ballCount,$("#numberofballs").text(ballCount),$("#timetotal").text(timeInterval/1E3),$("#timeavr").text(avrOf(intervals)/1E3),$("#timemax").text(maxOf(intervals)/1E3),$("#timemin").text(minOf(intervals)/1E3),$("#missedballs").text(sumOf(missed)),$("#windowsize").html(reportWindowSize()),
$("#reportfinishtime").text(timeFinished.toLocaleDateString()+" "+timeFinished.toLocaleTimeString()),"BGM ON"==$("#toggleBGM").text()?soundBGM.fade(1,0,1500):soundBGM.stop(),setTimeout(showGameReport,2E3)):(balls[0].myTurn(),Ball.currentTurn=0)}};function reportWindowSize(){var a=windows.length;return 1==a?"<b>"+windows[0][0]+" x "+windows[0][1]+"</b> (not resized)":"<b>"+windows[a-1][0]+" x "+windows[a-1][1]+"</b> (final size)"}
function maxOf(a){switch(a.length){case 0:return alert("Error of function [maxOf()]: Empty array!"),null;case 1:return a[0];default:for(var b=a[0],c=1;c<a.length;c++)a[c]>b&&(b=a[c]);return b}}function minOf(a){switch(a.length){case 0:return alert("Error of function [minOf()]: Empty array!"),null;case 1:return a[0];default:for(var b=a[0],c=1;c<a.length;c++)a[c]<b&&(b=a[c]);return b}}
function avrOf(a){switch(a.length){case 0:return alert("Error of function [avrOf()]: Empty array!"),null;case 1:return a[0];default:for(var b=0,c=0;c<a.length;c++)b+=a[c];return Math.floor(b/a.length)}}function sumOf(a){switch(a.length){case 0:return alert("Error of function [sumOf()]: Empty array!"),null;case 1:return a[0];default:for(var b=0,c=0;c<a.length;c++)b+=a[c];return b}}
var divOnMouseOut=function(a){},colorLibrary={yellows:"gold yellow lightyellow lemonchiffon lightgoldenrodyellow papayawhip moccasin peachpuff palegoldenrod khaki darkkhaki".split(" "),pinks:"pink lightpink hotpink deeppink palevioletred mediumvioletred".split(" "),purples:"lavender thistle plum orchid violet fuchsia magenta mediumorchid darkorchid darkviolet blueviolet darkmagenta purple mediumpurple mediumslateblue slateblue darkslateblue rebeccapurple indigo".split(" ")};
function randomColor(){var a;if(0==arguments.length)return"rgb("+(Math.floor(76*Math.random())+175)+","+(Math.floor(76*Math.random())+175)+","+(Math.floor(76*Math.random())+175)+")";switch(arguments[0].toLowerCase()){case "yellows","yellow":return a=colorLibrary.yellows.length,colorBallBorder="blue",a=Math.floor(Math.random()*a),colorLibrary.yellows[a];case "purples","purple":return a=colorLibrary.purples.length,colorBallBorder="gold",a=Math.floor(Math.random()*a),colorLibrary.purples[a];case "pinks",
"pink":return a=colorLibrary.pinks.length,colorBallBorder="Aqua",a=Math.floor(Math.random()*a),colorLibrary.pinks[a]}}function randomRadius(a,b){0==arguments.length&&(a=100);var c=1==arguments.legnth?Math.floor(Math.random()*a):Math.floor(Math.random()*a)+b;return 0<c%2?c+1:c}
function Ball(){this.selected=!1;this.selectedTime=new Date;this.radius=randomRadius(75,10);this.vLeft=Math.floor(Math.random()*window.innerWidth);this.vTop=Math.floor(Math.random()*window.innerHeight);this.vRight=this.vLeft+2*this.radius-1;this.vBottom=this.vTop+2*this.radius-1;this.vRight>=window.innerWidth&&(this.vLeft=window.innerWidth-2*this.radius-1,this.vRight=this.vLeft+2*this.radius-1);this.vBottom>=window.innerHeight&&(this.vTop=window.innerHeight-2*this.radius-1,this.vBottom=this.vTop+
2*this.radius-1);this.moveX=Math.floor(8*Math.random())-4;this.moveX=0==this.moveX?4:this.moveX;this.moveY=Math.floor(8*Math.random())-4;this.moveY=0==this.moveY?-4:this.moveY;this.ball=document.createElement("div");this.ball.setAttribute("class","bouncingball");this.ball.setAttribute("onmouseover","divOnMouseOver(this)");this.ball.style.left=this.vLeft+"px";this.ball.style.top=this.vTop+"px";var a=randomColor();this.ball.style.backgroundColor=a;this.borderColor=colorReverse($(this.ball).css("backgroundColor"));
this.ball.style.borderColor=this.ball.style.backgroundColor;this.ball.style.width=2*this.radius+"px";this.ball.style.height=2*this.radius+"px";this.ball.style.borderRadius=Math.floor(this.radius)+"px"}Ball.prototype.currentTurn=0;Ball.prototype.myTurn=function(){this.selected=!0;this.selectedTime=new Date;this.ball.style.borderColor="rgb(255,80,80)";this.ball.style.borderWidth="3px";this.ball.style.borderStyle="dotted";timeChecked=new Date};
Ball.prototype.imNot=function(){this.selected=!1;this.ball.style.borderColor=this.ball.style.backgroundColor;this.ball.style.borderWidth="1px";this.ball.style.borderStyle="solid"};
Ball.prototype.move=function(){this.vLeft+=this.moveX;0>=this.vLeft&&(this.vLeft=0,this.moveX*=-1);this.vTop+=this.moveY;0>=this.vTop&&(this.vTop=0,this.moveY*=-1);this.vRight=this.vLeft+2*this.radius-1;this.vBottom=this.vTop+2*this.radius-1;this.vRight>=window.innerWidth&&(this.vLeft=window.innerWidth-2*this.radius-1,this.vRight=this.vLeft+2*this.radius-1,this.moveX*=-1);this.vBottom>=window.innerHeight&&(this.vTop=window.innerHeight-2*this.radius-1,this.vBottom=this.vTop+2*this.radius-1,this.moveY*=
-1);this.ball.style.left=this.vLeft+"px";this.ball.style.top=this.vTop+"px"};Ball.prototype.rePosition=function(){var a=!1;this.vLeft+this.radius>window.innerWidth&&(this.vLeft=window.innerWidth-this.radius-1,a=!0);this.vTop+this.radius>window.innerHeight&&(this.vTop=window.innerHeight-this.radius-1,a=!0);a&&(this.ball.style.left=this.vLeft+"px",this.ball.style.top=this.vTop+"px")};
function moveBalls(){var a=new Date;1<balls.length&&balls[Ball.currentTurn].selected&&a-balls[Ball.currentTurn].selectedTime>=timeToNext&&(missedBalls++,addBallOnMissed&&addBall(),balls[Ball.currentTurn].imNot(),Ball.currentTurn>=balls.length-1?Ball.currentTurn=0:Ball.currentTurn++,balls[Ball.currentTurn].myTurn());for(var b in balls)balls[b].move(),intervals.length&&$("#timeinterval").text(avrOf(intervals)/1E3),document.getElementById("timefinish").innerHTML=getTimeStamp()}
function getTimeStamp(a){var b;if(0<arguments.length){if(1==a&&(timeChecked=b=timeStarted=new Date),2==a&&(b=timeFinished=new Date),3==a)return timeInterval=timeFinished-timeStarted,timeInterval/1E3}else b=new Date;return""+(addZero(b.getHours())+":"+addZero(b.getMinutes())+":"+addZero(b.getSeconds())+'.<span style="font-size:11pt; color:#444;">'+addZero(Math.floor(b.getMilliseconds()/10))+"</span>")}function addZero(a){return 10>a?"0"+a:a}
function rotateBalls(a){0==a?balls.push(balls.shift()):balls.unshift(balls.pop())}
function startGame(){ballCount=1*document.getElementById("ballcount").value;$("#gameresult").slideUp();for(var a=1;a<=ballCount;a++){var b=new Ball;document.body.appendChild(b.ball);$(b.ball).hide();$(b.ball).slideDown(500);balls.push(b)}ballsKilled=[];timer=setInterval(moveBalls,ballSpeed);document.getElementById("timestart").innerHTML=getTimeStamp(1);document.getElementById("ballsleft").innerHTML=balls.length;document.getElementById("timefinish").innerHTML="";document.getElementById("timeinterval").innerHTML=
"?";document.getElementById("control").style.visibility="hidden";document.getElementById("control2").style.visibility="hidden";document.getElementById("ballcount").value=ballCount;Ball.currentTurn=0;balls[Ball.currentTurn].myTurn();missedBalls=0;missed=[];intervals=[];windows=[];windowStamp();"BGM ON"==$("#toggleBGM").text()&&soundBGM.play()}
function addBall(){var a=new Ball;document.body.appendChild(a.ball);$(a.ball).hide();$(a.ball).slideDown(400);balls.push(a);ballCount++;ballsMin=ballCount;document.getElementById("ballsleft").innerHTML=balls.length;document.getElementById("ballcount").value=ballCount;soundNewBall.play()}function pauseGame(){null!=timer?(clearInterval(timer),timer=null):resumeGame()}function resumeGame(){null==timer?timer=setInterval(moveBalls,ballSpeed):pauseGame()}
function correctBallsInput(){var a=document.getElementById("ballcount"),b=1*a.value;b<=ballsMin?a.value=ballsMin:b>ballsMax&&(a.value=ballsMax)}function reAlignCopyright(){var a=document.getElementById("copyright").style;a.top=window.innerHeight-20+"px";a.width=window.innerWidth-20+"px";for(var b in balls)balls[b].rePosition();windowStamp();reAlignGameResult()}
function controlAddBall(){addBallOnMissed?(addBallOnMissed=!1,$("#togglePenalty").text("Penalty OFF")):(addBallOnMissed=!0,$("#togglePenalty").text("Penalty ON"));soundControlButton.play()}function controlBGM(){"BGM ON"==$("#toggleBGM").text()?(soundBGM.stop(),$("#toggleBGM").text("BGM OFF")):(soundBGM.play(),$("#toggleBGM").text("BGM ON"));soundControlButton.play()}
function reAlignGameResult(){var a=document.getElementById("gameresult").style;a.left=Math.floor((window.innerWidth-500)/2)+"px";a.top="150 px"}window.onload=function(){reAlignCopyright();document.getElementById("ballcount").value=ballCount;$("#gameresult").hide()};